### ISSUE TITLE
remapping Esc

### ISSUE THREAD

**Issue by assemnical** [atom/vim-mode#334]
I remapped  'jk' and 'kj' to activate command mode.
 
>'.editor.vim-mode:not(.command-mode)':
  'j k': 'vim-mode:activate-command-mode'
  'k j': 'vim-mode:activate-command-mode'

However if I just press 'k' or 'j' followed by another letter, the 'k' or 'j' doesn't appear. How can I overcome this problem?

**Comment by BallisticPain** [comment]
I have been unable to get jj to work for typing "j" and also using "jj" to get me out of command mode. :(

I feel this shouldn't be so difficult. I have seen people reference a "timeout", but have been unable to find this anywhere in the settings for either Vim Mode nor Atom.

Thoughts?

Thanks!
J

**Comment by pelachile** [comment]
@BallisticPain where did you find the misspelling? I have tried and tried and I can't get jj to work. It's the only thing that prevents me from using atom, I'm just to used to my vim settings.

**Comment by BallisticPain** [comment]
@pelachile, I'll copy and paste below what I have that's working. I use jj constantly and it was imperative that I got it working as well so I fully understand your frustration.

I personally mis-spelled a portion of the ~/.atom/init.coffee script. I didn't copy and paste, I just typed it in.
```
# Your init script
#
# Atom will evaluate this file each time a new window is opened. It is run
# after packages are loaded/activated and after the previous editor state
# has been restored.
#
# An example hack to make opened Markdown files always be soft wrapped:
#
# path = require 'path'
#
# atom.workspaceView.eachEditorView (editorView) ->
#   editor = editorView.getEditor()
#   if path.extname(editor.getPath()) is '.md'
#     editor.setSoftWrap(true)
#

atom.workspaceView.command 'insert-incomplete-keybinding', (e)->
    if oe = e.originalEvent && e.originalEvent.originalEvent
        char = String.fromCharCode(oe.which)
        char = char.toLowerCase() unless oe.shift
        atom.workspace.activePaneItem.insertText(char)
```

I misspelled the .workspace portion.

Here's my ~/.atom/keymap.cson (I was originally modifying the one in the package directly, and this wasn't working as well as modifying my home directory version)...
```
# Your keymap
#
# Atom keymaps work similarly to stylesheets. Just as stylesheets use selectors
# to apply styles to elements, Atom keymaps use selectors to associate
# keystrokes with events in specific contexts.
#
# You can create a new keybinding in this file by typing "key" and then hitting
# tab.
#
# Here's an example taken from Atom's built-in keymap:
#
# '.editor':
#   'enter': 'editor:newline'
#
# '.workspace':
#   'ctrl-P': 'core:move-up'
#   'ctrl-p': 'core:move-down'
#
'.editor.vim-mode.insert-mode':
    'j': 'insert-incomplete-keybinding'

'.vim-mode.insert-mode:not(.mini)':
  'j j': 'vim-mode:activate-command-mode'
```
One thing I will also note here is that I believe the order of these two insertions matters. The other note is that if you want to type a 'j' while in insert mode, type it and then the next letter and they'll both appear. Otherwise you must wait for the timeout to occur to see the 'j' appear.

I hope this helps,
Jarvis

**Comment by JacobHTran** [comment]
atom seems to have a new process to add custom command.  I have been playing with atom for all of 10 mins, but in order to achieve this functionality without using the deprecated atom.workspaceView.command I implement the insert-incomplete-keybinding as such: 

    atom.commands.add 'atom-text-editor', 'insert-incomplete-keybinding', (e)->
      oe = e.originalEvent
      char = String.fromCharCode(oe.which)
      char = char.toLowerCase() unless oe.shift
      atom.workspace.activePaneItem.insertText(char)`

**Comment by rdlugosz** [comment]
I was still seeing odd delays with this method and implemented things in a slightly different way. Note that I prefer to use `kj` to exit insert mode rather than `jk` or `jj`, but you should be able to modify this for your own approach.

```
#keymap.cson
'.editor.vim-mode.insert-mode':
  'j': 'exit-insert-mode-if-proceeded-by-k'
```

```
#init.coffee
atom.commands.add 'atom-text-editor', 'exit-insert-mode-if-proceeded-by-k': (e) ->
  editor = @getModel()
  pos = editor.getCursorBufferPosition()
  range = [pos.traverse([0,-1]), pos]
  lastChar = editor.getTextInBufferRange(range)
  if lastChar != "k"
    e.abortKeyBinding()
  else
    editor.backspace()
    atom.commands.dispatch(e.currentTarget, 'vim-mode:activate-command-mode')
```

While this isn't quite as flexible, there are no "timeout" related issues or visual delays in not having the `j` (or in my case, `k`) char appear on the screen until the next keypress.  Note that using the `event.abortKeyBinding()` is the preferred way to jump out of your key bindings and let the keystroke pass through to the editor (see: https://atom.io/docs/api/v0.187.0/KeymapManager). Thoughts?

**Comment by Robert-Wett** [comment]
+1 @rdlugosz  - working great for me, using `jk` to exit insert mode. For the lazy:

```
#keymap.cson
'.editor.vim-mode.insert-mode':
  'k': 'exit-insert-mode-if-proceeded-by-j'

#init.coffee
atom.commands.add 'atom-text-editor', 'exit-insert-mode-if-proceeded-by-j': (e) ->
  editor = @getModel()
  pos = editor.getCursorBufferPosition()
  range = [pos.traverse([0,-1]), pos]
  lastChar = editor.getTextInBufferRange(range)
  if lastChar != "j"
    e.abortKeyBinding()
  else
    editor.backspace()
    atom.commands.dispatch(e.currentTarget, 'vim-mode:activate-command-mode')
```

**Comment by JerseyMilker** [comment]
I agree.  It should be as easy as:
```'atom-text-editor.vim-mode':
  'j k': 'vim-mode:reset-command-mode'```

**Comment by ahmadseleem** [comment]
The best and simplest until this is supported natively by Atom:
Is the one by: @Robert-Wett 
because the the one by @garcg doesn't work if yo wanna map escape to something like =>
```
 , ,
```
So, the final solution is as @Robert-Wett except he didn't add escape for visual mode in the mapping:

```
#keymap.cson

#................................................
# Escape
#................................................
'atom-text-editor.editor.vim-mode.insert-mode':
  ',': 'exit-insert-mode-if-proceeded-by-j'

'atom-text-editor.vim-mode.visual-mode:not(.mini)':
  ', ,': 'vim-mode:activate-command-mode'
  'v': 'vim-mode:activate-command-mode'
```

It's still not perfect because it just wait for the second letter for ever....!!!
it should be just a half a second or so then inserts the char and return...

**Comment by ahmadseleem** [comment]
Like:
 ```js
 setTimeout(doStuff, 50); //wait 50 millisecnds then recheck
 return;
```

**Comment by bronson** [comment]
Is this a dupe of #221?

**Comment by JerseyMilker** [comment]
Not sure.  Some people like the simultaneous "j+k", other people like the slightly offset "j" then "k" in quick succession.  Either way, I'm not sure either is as well fleshed out as in other Vim emulators (Vintageous for Sublime Text, etc).

**Comment by rdlugosz** [comment]
@bronson It's possibly a dup, but since there's been a lot more discussion (and proposed workarounds) here I'd suggest closing that issue and keeping this one open. That issue may be tougher for folks to find since the subject is referencing a specific third-party app for remapping keys.

**Comment by lazybios** [comment]
@philk  Thank you ! It's works for me too! I can continue stay in the Atom with my habits. :grin:

**Comment by schmittyjd** [comment]
how would you go about the setTimeout in coffee script?

**Comment by liyaodong** [comment]
`init.coffee`

```
atom.commands.add 'atom-text-editor', 'custom:wait-key-press', (e)->
  oe = e.originalEvent
  char = String.fromCharCode(oe.which)
  char = char.toLowerCase() unless oe.shift
  atom.workspace.getActivePaneItem().insertText(char)
```

`keymap.cson`

```
'atom-text-editor.vim-mode.insert-mode':
  'j': 'custom:wait-key-press'

'.vim-mode.insert-mode:not(.mini)':
  'j j': 'vim-mode:activate-command-mode'
```

worked for me , atom version `0.207.0`

**Comment by ahmadseleem** [comment]
No, I don't think this works, completely.
Now, you can't type *j*

**Comment by liyaodong** [comment]
But it works for me , my atom version is `0.208.0)` , I can type `j` and if I type `jasdfasdf` the `j`  will immediately appear . if I just type `j` wait 2s `j` will appear . 

@ahmadseleem

**Comment by ahmadseleem** [comment]
Yes it does work now!
I'm sorry, I didn't wait 2s :)
Anyway to control the time ?
Seriously, curious! Like 1 sec ?

Also, it doesn't insert comma in my case. It inserts 1/4 like a Unicode char,

**Comment by liyaodong** [comment]
Sorry, I don't know how to control the delay , In fact I think it doesn't matter , because we usually type a `word` , A few cases we just type `j` . and the comma ... I can type it , Maybe because other reason : )

**Comment by ahmadseleem** [comment]
No, I think because the comma is not an alphabetic char.
So, for example you can't convert to lower case as in your solution.

**Comment by liyaodong** [comment]
so clever , we can detect char code, if it's character like `abcd` then convert it

**Comment by pelachile** [comment]
Last solutions is not working on Atom 0.209.0. J will not show up.

**Comment by damassi** [comment]
Neither does it work for 0.211.0

**Comment by rdlugosz** [comment]
Just confirmed that [my solution](https://github.com/atom/vim-mode/issues/334#issuecomment-85603175) to this is still working fine in version `0.211.0`.

**Comment by damassi** [comment]
@rdlugosz - Thanks so much!  You're right; works great AND fast.  Finally able to leave MacVim for the modern world!

**Comment by ahmadseleem** [comment]
@rdlugosz Yes, your solution is the one I use for a while.

**Comment by stv8** [comment]
@rdlugosz solution works well, but do you know how you can stop it from backspacing? In other words is there a way I can press `jk` and still stay in place rather than move one character back?

**Comment by rdlugosz** [comment]
Yes, `moveRight()` should work, but doesn't this give you behavior that is inconsistent with Vim? In Vim, if I type the word "testing" and hit `ESC` (or `kj`), the cursor is placed on the `g` character.

**Comment by stv8** [comment]
@rdlugosz yeah it is a bit inconsistent but I kind of like it :)

**Comment by rdlugosz** [comment]
haha - that's cool, just making sure I wasn't missing something. :+1:

**Comment by rufo** [comment]
@rdlugosz - works great, thanks!

Just as a note for anyone else checking out Atom post-1.0, it looks like you need to change`'.editor.vim-mode.insert-mode'` to  `'atom-text-editor.vim-mode.insert-mode'` in `keymap.cson` to avoid a deprecation warning. (I kept accidentally leaving the period at the beginning and not having it work - turns out, just like it says it needs a _tag_ selector, not a _class_ selector :stuck_out_tongue:)

**Comment by stv8** [comment]
@rufo when I changed `'.editor.vim-mode.insert-mode'` to `'atom-text-editor.vim-mode.insert-mode'` my `jk` binding broke

**Comment by stv8** [comment]
@rufo thanks for the info! I had it as a class as well and was wondering why it wasn't working :+1:

**Comment by rufo** [comment]
@stv8 yep, totally did the same thing. Cheers! :beers:

**Comment by rdlugosz** [comment]
Thanks @rufo, I've made an edit to the original comment to fix the deprecation warning.

**Comment by DanielAndreasen** [comment]
Noob here. Where should I save the second part of the solution of @rdlugosz, i.e. the function that checks if it is preceded by `k`? If I save it in `keymap.cson` after the first part, atom fails to load this file.

**Comment by rufo** [comment]
@DanielAndreasen Drop that in your `init.coffee` file - easiest way is to go to the main Atom menu and pick "Open Your Init Script." (That's where it is on OS X; not sure where it is on Windows/Linux.)

**Comment by damassi** [comment]
@DanielAndreasen, yup, all of your config files are available from the Atom dropdown menu

**Comment by DanielAndreasen** [comment]
Thanks @rufo and @damassi. In vim I have mapped both `jk` and `kj` as smash escape. When I try to do this (making two functions in init.coffee) I end up not being able to type `k`... However, it works when I only have the functions first suggested (with preceding k).

**Comment by rufo** [comment]
@DanielAndreasen: I didn't have that problem when I tested it real quick, but I did notice only one of them worked. I don't know the details as I'm only just prodding at Atom myself, but I could certainly see them interfering slightly. My gut says the best thing to do might be to map both J and K to the same function, then modify that function to figure out if the preceding character was the opposite, and then exit insert mode if that's the case.

**Comment by DanielAndreasen** [comment]
I was about to give up, because the function in `init.coffee` screws up things for me. I try the first approach and it works for me (Atom 1.0.0)

    'atom-text-editor.vim-mode.insert-mode':
      'j k': 'vim-mode:reset-command-mode'
      'k j': 'vim-mode:reset-command-mode'

Without putting anything else, this works perfect. Remember the space between `j` and `k`.

**Comment by zephraph** [comment]
Hey @maxbrunsfeld, this is the issue I was talking to you about on the bus.

**Comment by cwonrails** [comment]
@DanielAndreasen's snippet worked for me; thanks!

**Comment by ndland** [comment]
Thank you @DanielAndreasen, this was what I was looking for.

**Comment by DanielAndreasen** [comment]
You are both welcome! :+1:

**Comment by zephraph** [comment]
So wait, this issue is fixed now?

**Comment by ndland** [comment]
It doesn't fix anything for Visual mode, but it works perfectly if you're only using the remap for Insert mode. I was originally using
```cson
'atom-text-editor.vim-mode:not(.command-mode)':
  'escape': 'vim-mode:activate-command-mode'
```
Which works, but when visually selecting a line, and using j to scroll down, it was delayed because it was checking to see if we were trying to escape back to normal mode.

**Comment by zephraph** [comment]
Ahh, I see. Well, it's getting there it seems.

**Comment by DanielAndreasen** [comment]
@ndland: I had the same problem when I tried to use `jk` as `Esc` for normal vim, so I only use it now for insert mode. Also if you press down too much, and have to go back up, it is annoying it will escape visual mode, and go to normal mode. Just my opinion.

**Comment by zephraph** [comment]
@DanielAndreasen I kinda assumed that would be the case. I just ```fj``` for mine so it's not as big of a deal. It works well even in regular vim.

**Comment by ndland** [comment]
@zephraph I see what you mean, I'm getting the same behavior. :confused:

**Comment by rdlugosz** [comment]
@DanielAndreasen Not sure why you're having trouble with the function in your init file. Just verified everything is still working correctly on my copy of Atom & it is. You can try out my config files in place of your own; I keep them all in [my dotfiles repo](https://github.com/rdlugosz/dotfiles/tree/master/atom).

@DanielAndreasen @ndland The problem with mapping multiple keys as you suggest gets back to the issue discussed much earlier in this thread: it causes a delay while Atom is waiting for input to see if you are going to trigger the keymap. With the snippet you each list above (mapping `j j`, etc), you cannot enter words beginning with the letter `j`! Try typing the word 'just' in insert mode with your mapping and I think you'll see `ust` appear in the buffer (at least, that's what I see).

As far as using these alternative `ESC` mappings for exiting Visual mode, I don't think that is a common use case. If you are in Visual mode, typically you would exit by performing an action on the selected text. Or, if you'd like to exit visual mode without an action, you can just press `v` again (or `ESC`, obviously). _BTW, here are some other tips on [Avoiding ESC](http://vim.wikia.com/wiki/Avoid_the_escape_key)._

**For now, I believe [my solution presented above](https://github.com/atom/vim-mode/issues/334#issuecomment-85603175) is the only way to escape out of insert mode via character key mappings like `jj` `jk` `kj` or `fd` without introducing bad side effects.**

**Comment by ndland** [comment]
@rdlugosz Thank you for clarifying. I missed that comment from above, I have tested your solution, and it is working as I expect it to :+1:.

**Comment by rdlugosz** [comment]
np!

**Comment by DanielAndreasen** [comment]
@rdlugosz I'm really not sure what is going on anymore. Now your solution works. However, I had to restart atom. Otherwise, I couldn't write either `j` or `k`. After the restart it works though.
I also confirm the problem with my naïve solution. I have to hit either `j` or `k` twice in order to write that character.

**Comment by rdlugosz** [comment]
No worries, glad you got it figured out! Also, I think most of us started with your solution and thought we had it solved until trying to type a j-word... turns out there aren't a lot of those in most programming! :beers:

**Comment by DanielAndreasen** [comment]
But when you write a paper in e.g. LaTeX, you quickly realize the limitations. :beers:

**Comment by chrisandharris** [comment]
With version 0.56, the atom dispatch command needs to be vim-mode:activate-normal-mode instead of activate-command-mode.

```
#init.coffee
atom.commands.add 'atom-text-editor', 'exit-insert-mode-if-preceded-by-j': (e) ->
  editor = @getModel()
  pos = editor.getCursorBufferPosition()
  range = [pos.traverse([0,-1]), pos]
  lastChar = editor.getTextInBufferRange(range)
  if lastChar != "j"
    e.abortKeyBinding()
  else
    editor.backspace()
    atom.commands.dispatch(e.currentTarget, 'vim-mode:activate-normal-mode')
```

**Comment by bronson** [comment]
Good catch.  Seems like there's enough demand to include this command in vim-mode directly?  (or one like it, where maybe lastChar can be parameterized?)

**Comment by maxbrunsfeld** [comment]
We're planning on fixing this issue with the core key-mapping system (so that you can just do `j j: 'vim-mode:activate-normal-mode'`) as part of our big bug-fixing effort this month: https://github.com/atom/atom/issues/7995.

**Comment by ahmadseleem** [comment]
@maxbrunsfeld Cool!

**Comment by babygau** [comment]
Just a quick update, the latest version vim-mode 0.56.0 changed `command mode` to `normal mode` so anyone using @rdlugosz's solution should update their `init.coffee` config to the following:

```coffeescript
atom.commands.add 'atom-text-editor', 'exit-insert-mode-if-proceeded-by-j': (e) ->
  editor = @getModel()
  pos = editor.getCursorBufferPosition()
  range = [pos.traverse([0,-1]), pos]
  lastChar = editor.getTextInBufferRange(range)
  if lastChar != "j"
    e.abortKeyBinding()
  else
    editor.backspace()
    atom.commands.dispatch(e.currentTarget, 'vim-mode:activate-normal-mode')
```

**Comment by damassi** [comment]
@chrisandharris - did you do anything else to get it to work?  Replacing what I had with your snippet, it seems as though I can no longer exit insert mode.

**Comment by rdlugosz** [comment]
I've updated my code above to use the new mode name (which is a good rename, btw... much more descriptive!). Cool to see that the Atom team is looking at addressing this in a more holistic way soon!

**Comment by maxbrunsfeld** [comment]
We've finally fixed this bug. In the next Atom release (v1.0.3), you'll just have to do this:

```coffee
'atom-text-editor.vim-mode.insert-mode':
  'j j': 'vim-mode:activate-normal-mode'
```

**Comment by ahmadseleem** [comment]
@maxbrunsfeld 👍

**Comment by kylesezhi** [comment]
Huzzah!

**Comment by JesseLeite** [comment]
Nice!  Thank you @maxbrunsfeld ...This is so much better!

It's still slightly awkward because it causes the `j` key to hang for a second while it waits for a second input.  In Sublime, the first `j` is immediately printed to the buffer, then if a second input matches `j` within a second or two, the `j` is removed from the buffer and the command is executed.  Not sure if this is possible in Atom, but it'd make arpeggio keymappings feel much more natural in my opinion.  Is this possible in Atom?

**Comment by JesseLeite** [comment]
As a followup, I'm going to use @rdlugosz's method, as it seems to feel much better.  I know it's harder to edit the key mapping, but it gets rid of that annoying delay.

Too bad Atom doesn't handle multi key mappings this way, where a `'j k'` keymap holds off on execution until it reads the second key (the `k` in this case), then checks the preceeding key for a match (a `j` in this case).  This would stop the Atom from hanging when the first key is hit.

**Comment by pelachile** [comment]
I don't think @rdlugosz solution works anymore after updating to 1.0.9. 




1. simply type j and the error appears. 

**Atom Version**: 1.0.9
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'getTextInBufferRange' of undefined

```
At /Users/MacPro/.atom/init.coffee:17

TypeError: Cannot read property 'getTextInBufferRange' of undefined
  at atom-text-editor.atom.commands.add.exit-insert-mode-if-preceded-by-j (/Users/MacPro/.atom/init.coffee:17:27)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -4:34.8.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -4:32.7.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -4:32.4.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -4:31.7.0 vim-mode:delete-right (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -4:31.5.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -4:31.2.0 vim-mode:delete-right (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -4:30.1.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -4:29.3.0 ex-mode:open (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -4:29.3.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -4:29 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -4:29 blur (atom-text-editor.editor.mini.is-focused)
  2x -4:25.4.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -4:24.8.0 vim-mode:insert-below-with-newline (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -4:24 exit-insert-mode-if-preceded-by-j (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
 10x -4:18.5.0 blur (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:01.8.0 exit-insert-mode-if-preceded-by-j (atom-text-editor.editor.vim-mode.insert-mode.is-focused)

**Comment by JesseLeite** [comment]
I'm using @rdlugosz solution, but set it up for `j k`.  I'm also in Atom 1.0.9 and it works fine here.

Keymap:
```
'atom-text-editor.vim-mode.insert-mode':
    'k': 'exit-insert-mode-if-preceded-by-j'
```

Init Script:
```
atom.commands.add 'atom-text-editor', 'exit-insert-mode-if-preceded-by-j': (e) ->
    editor = @getModel()
    pos = editor.getCursorBufferPosition()
    range = [pos.traverse([0,-1]), pos]
    console.log(range)
    lastChar = editor.getTextInBufferRange(range)
    if lastChar != "j"
        e.abortKeyBinding()
    else
        editor.backspace()
        atom.commands.dispatch(e.currentTarget, 'vim-mode:activate-normal-mode')
```

If those still don't work for you, maybe another script or something is interfering?

**Comment by rdlugosz** [comment]
@pelachile Just tried my existing solution and in current Atom (1.0.10) it works fine. Maybe there's a typo in your init script? Could you try starting with a fresh copy of the keymap and init script? :confused: 

@maxbrunsfeld Definitely a step in the right direction, but I agree with @JesseLeite — the first char in the map not appearing right away is a significant drawback that is avoided with the approach I've been using ([see above](https://github.com/atom/vim-mode/issues/334#issuecomment-85603175)). Any thoughts as to whether generically implementing sequential-key mappings in a way similar to how I've done it would be possible in the Atom codebase?

**Comment by chrisUsick** [comment]
The solution mentioned by @JesseLeite is not working for me in a fresh install of atom version 1.0.10  with vim-mode. Is there anything else that needs to be done to make this work?

**Comment by JesseLeite** [comment]
@chrisUsick It's working for me in 1.0.11 on OSX, exactly as pasted above.

**Comment by chrisUsick** [comment]
Okay, the command is performing the backspace, but it doesn't change the mode for me.

**Comment by JesseLeite** [comment]
Weird.  A backspace, but not switching back to normal model?  I can't replicate this.

**Comment by chrisUsick** [comment]
Okay, just wanted to post in case others experience the same error

**Comment by Robert-Wett** [comment]
I'm at 1.1.0 Atom on OSX, and I'm now getting the same behavior as @chrisUsick - the `jk` characters are deleted but it fails to escape insert mode

**Comment by JesseLeite** [comment]
@Robert-Wett Weird. I'm also Atom 1.1.0 for OSX, and `jk` works fine using the method described in my above comment from Aug 29th.

**Comment by sarink** [comment]
Thanks @JesseLeite !

**Comment by ipstone** [comment]
Thanks @JesseLeite , it works for me on atom 1.3.2, windows.

I think we should package the solution as a function such as:
 "reset-normal-mode-by-keycomb",   or "reset-normal-mode-keycomb"
so that people can just add in the keymap: k: 'vim-mode: reset-normal-mode-keycomb(j)'

or something similar to that extent, so that 'jk' would becoming the remap of Esc.

**Comment by JesseLeite** [comment]
@ipstone: Great idea. I'll try to package it up soon.  It's one of those things where I just pasted to init script and forgot about it.  Would be even easier for new users if there was package to implement the script though.

**Comment by rdlugosz** [comment]
@JesseLeite @ipstone I think that's a great idea, but when I last looked at this it wasn't clear how you can pass a parameter to a function in a keymap. That's why I ended up hard coding the key into the function name, i.e., `exit-insert-mode-if-preceded-by-k`. 

If it _is_ possible to do this, I'd propose naming the function `activate-normal-mode-if-preceded-by(char)` so that it's easy (easier) to understand what's going on when you look at someone's keymapping, e.g.:

```
# User's keymap.cson:

# To map 'kj' as ESC
'atom-text-editor.vim-mode.insert-mode':
  'j': 'activate-normal-mode-if-preceded-by(k)'

# To map 'jk' as ESC
'atom-text-editor.vim-mode.insert-mode':
  'k': 'activate-normal-mode-if-preceded-by(j)'

# To map 'jj' as ESC
'atom-text-editor.vim-mode.insert-mode':
  'j': 'activate-normal-mode-if-preceded-by(j)'
```

I think that makes it really clear what's going on, but again, can you actually pass a parameter this way? I suspect not, since the [vim-surround](https://github.com/gepoch/vim-surround) package would benefit from this approach but doesn't use it. In fact, the author of that package goes to the extent of [_dynamically building_](https://github.com/gepoch/vim-surround/blob/master/keymaps/surround.cson) individual commands and generating the keymaps. Maybe something like that could be done for our needs based on options the user can set in the package settings? Not sure how you'd go about this without it getting out of hand...

Alternatively, maybe the best option is to document this keymap+init function approach right in the package readme. I'll set about creating a PR for that.

**Comment by JesseLeite** [comment]
I won't have time to mess with this for a few weeks anyway.  If anyone else if up for packaging it out, by all means!  If not, it's on my list.

@rdlugosz I agree about naming.  Hadn't thought that far.  I just like the idea of extracting this to a package instead of vim users having to stumble across threads like this for init script.

Never know, maybe core vim-mode maintainers would be interested in adding this as option?  Maybe it's too specialized of a feature, idk.

**Comment by RafaelCosman** [comment]
Thanks for your work on this! I've tried a bunch of the posts in this thread and haven't gotten any of them to work. Looking forward to a package that fixes this.

**Comment by ebylund** [comment]
@rdlugosz Great solution! I've used Macvim for the past year, all the while getting used to my 'jk' esc mapping. I'd been having a problem switching to Atom because of the lag it introduced. I'd tried other solutions, but none seemed to work, Thanks again!

**Comment by tomesh** [comment]
@Robert-Wett unfortunately it seems this snippet is not working anymore (Linux Debian, Atom v. 1.5.3)

**Comment by rdlugosz** [comment]
@tomesh @Robert-Wett Are you saying my snippet (the one documented in [the PR](https://github.com/atom/vim-mode/issues/946)) no longer works? Just tried it in Atom 1.5.3 (OS X) and it seems to work fine...

**Comment by tomesh** [comment]
@rdlugosz No, i mean this snippet:

`'atom-text-editor.vim-mode.insert-mode':
'j k': 'vim-mode:activate-normal-mode'`

But actually non of the snippets posted in this thread is working for me. Solutions with init script functions, solutions without it... no chance to make it operational.

I have tried reinstallation, disabling the other plugins etc . without any success. An I dunno how to debug it.

**Comment by tomesh** [comment]
@rdlugosz well... only solution which works for me is upgrade to beta version (1.6.0-beta4)

**Comment by kylesezhi** [comment]
I have 1.5.3 and this keymap works for me:
`'atom-text-editor.vim-mode.insert-mode':
  'j k': 'vim-mode:activate-normal-mode'`

**Comment by Yohanna** [comment]
@kylesezhi Your kemap worked for me, thanks!

For the record, I'm using v. `1.5.4`

**Comment by JesseLeite** [comment]
@kylesezhi and @Yohanna that keymap always worked.  The issue is with the delay when typing anything like "jam" or "jesse".  There's a bad delay after hitting that `j` key while the keymap listener is waiting for a possible `k` to follow.

Other vim emulators do their check when you hit the second `k` input.  When `k` is hit, the emulator checks the previous key to see if it was a `j`, and if so enters vim mode.  This allows the vim emulator to handle the same key mapping without delay.

**Comment by rdlugosz** [comment]
Exactly. Avoiding the delay is precisely what my post above (and PR to have
this added to the Readme) is all about.

One step further that i think is worth considering is to just add the code
to the package itself and allow the user to specify their preferred two-key
mapping to exit insert mode via the vim-mode config screens. It's debatable
as to whether something like this belongs in the config gui, but mapping a
sequence like this is such a common thing that it could be justified.
(Assuming, of course, adding this to the config would allow users to skip
the business of adding the custom function to the init script.)

To be perfectly honest I'm not a daily Atom user so can't justify looking
into building this right now. When I do use Atom I'd like the mappings to
work properly, which is what my approach allows.

**Comment by kylesezhi** [comment]
Thanks for that explanation, @JesseLeite !

I agree - checking after the `k` in `jk` would be an improvement on the current way the system works. I'd love to see this in a future build of Atom.

**Comment by JesseLeite** [comment]
@kylesezhi well it would need to be built into the vim-mode package, not Atom core.  Until then, you can add @rdlugosz's [solution above](https://github.com/atom/vim-mode/issues/334#issuecomment-85603175) to your init script and keymap.

**Comment by vimniky** [comment]
haha this works now ! , just two line , neat ! thanks @maxbrunsfeld
'atom-text-editor.vim-mode.insert-mode':
  'j k': 'vim-mode:activate-normal-mode'

**Comment by denysdovhan** [comment]
Yep, but it still doesn't work well for non-american keyboards.

**Comment by Khangeldy** [comment]
After  remap to `k j` . It is hard to import  [sockjs](https://github.com/sockjs)

**Comment by mugukamil** [comment]
@denysdovhan Yes it is... :(

**Comment by rdlugosz** [comment]
While that's true, it's also true in Vim proper. Probably why the "official" way to leave insert mode is `ESC` instead of some combination of letters you may want to type. :)

Simple enough to add one additional check to the code to see if you might be typing something like 'sockjs' (look for a 'c' before the 'k') if this hits you a lot.

**Comment by garethderioth** [comment]
@denysdovhan Why it is that? I have an non-american keyboard and works well.

**Comment by denysdovhan** [comment]
@garethderioth I have no idea why. Now, I just use vim.
