### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by HarolddeBruijn** [atom/vim-mode#705]
/home/x/.atom/packages/vim-mode/lib/vim-state.coffee:556
- Hide Stack Trace

TypeError: undefined is not a function
  at getChangesSinceCheckpoint (/home/x/.atom/packages/vim-mode/lib/vim-state.coffee:556:6)
  at VimState.module.exports.VimState.deactivateInsertMode (/home/x/.atom/packages/vim-mode/lib/vim-state.coffee:409:15)
  at VimState.module.exports.VimState.activateCommandMode (/home/x/.atom/packages/vim-mode/lib/vim-state.coffee:375:6)
  at VimState.module.exports.VimState.resetCommandMode (/home/x/.atom/packages/vim-mode/lib/vim-state.coffee:474:6)
  at VimState.module.exports.VimState.processOpStack (/home/x/.atom/packages/vim-mode/lib/vim-state.coffee:261:12)
  at VimState.module.exports.VimState.pushOperations (/home/x/.atom/packages/vim-mode/lib/vim-state.coffee:224:8)
  at ViewModel.cancel (/home/x/.atom/packages/vim-mode/lib/view-models/view-model.coffee:15:17)
  at vim-command-mode-input.VimCommandModeInputElement.cancel (/home/x/.atom/packages/vim-mode/lib/view-models/vim-command-mode-input-element.coffee:53:16)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61

**Comment by maxbrunsfeld** [comment]
@HarolddeBruijn what version of Atom are you using? It looks like you may be using an old one. Could you upgrade to the latest versions of Atom and vim-mode and report whether the problem persists?

**Comment by HarolddeBruijn** [comment]
Indeed I was on 0.199.0
Just downloaded latest, apparently only the plugins have an outdated
message?

Met vriendelijke groet,

Harold de Bruijn
Wolfsmelkstraat 24
5262 DN  Vught
06 2222 1040

Op 18 jun. 2015 18:31 schreef "Max Brunsfeld" <notifications@github.com>:

**Comment by maxbrunsfeld** [comment]
Atom should be checking for updates automatically every few hours on Mac and Windows. Are you still seeing this error on the latest Atom?

**Comment by HarolddeBruijn** [comment]
Hi Max,

The error was resolved with updating, I downloaded the new x64 .deb from
atom.io.
Thank you for your help.

2015-06-18 19:57 GMT+02:00 Max Brunsfeld <notifications@github.com>:

> Atom should be checking for updates automatically every few hours on Mac
> and Windows. Are you still seeing this error on the latest Atom?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atom/vim-mode/issues/705#issuecomment-113238695>.
>



-- 
Harold de Bruijn
Wolfsmelkstraat 24
5262 DN  Vught
06-2222040

**Comment by lmartins** [comment]
Hi, Im running the latest versions for Atom and vim-mode and still getting this error. Anything else I can do?

**Comment by tlester** [comment]
I too am getting this error.  Just updated a few minutes ago (10:49 ET 6/19/15)

**Comment by tlester** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.199.0
**System**: Mac OS X 10.10.3
**Thrown From**: [vim-mode](https://github.com/atom/vim-mode) package, v0.53.0


### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/tlester/.atom/packages/vim-mode/lib/vim-state.coffee:556

TypeError: undefined is not a function
  at getChangesSinceCheckpoint (/Users/tlester/.atom/packages/vim-mode/lib/vim-state.coffee:556:6)
  at VimState.module.exports.VimState.deactivateInsertMode (/Users/tlester/.atom/packages/vim-mode/lib/vim-state.coffee:409:15)
  at VimState.module.exports.VimState.activateCommandMode (/Users/tlester/.atom/packages/vim-mode/lib/vim-state.coffee:375:6)
  at atom-text-editor.registerCommands.activate-command-mode (/Users/tlester/.atom/packages/vim-mode/lib/vim-state.coffee:64:36)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/tlester/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Users/tlester/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/tlester/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/tlester/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Users/tlester/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -3:14.2.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:41.9.0 window:update-available (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
 29x -0:13.3.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused)
  5x -0:09.4.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.is-focused)
     -0:07.8.0 core:move-left (atom-text-editor.editor.vim-mode.is-focused)
  3x -0:06.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused)
  3x -0:05.5.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused)
     -0:04.9.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.is-focused)
     -0:04.4.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused)
     -0:03.6.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused)
     -0:03.2.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.is-focused)
  7x -0:02.3.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused)
  4x -0:00.6.0 vim-mode:activate-command-mode (atom-text-editor.editor.vim-mode.is-focused)
```

### Config

```json
{
  "core": {},
  "vim-mode": {}
}
```

### Installed Packages

```coffee
# User
vim-mode, v0.53.0

# Dev
No dev packages
```

**Comment by HarolddeBruijn** [comment]
Tlesser,

You should update atom itself, I see you have version 0.199.0

Met vriendelijke groet,

Harold de Bruijn
Wolfsmelkstraat 24
5262 DN  Vught
06 2222 1040

Op 19 jun. 2015 16:51 schreef "tlester" <notifications@github.com>:

**Comment by maxbrunsfeld** [comment]
> You should update atom itself, I see you have version 0.199.0.

:+1:

> Hi, Im running the latest versions for Atom and vim-mode and still getting this error. Anything else I can do?

@lmartins Are you sure that it's *this same* error (same stack trace)? It shouldn't happen with the latest Atom. I'm guessing that it's slightly different. Could you open another issue?

**Comment by itkovian** [comment]
I am running 1.0, and got directed here for the 'same' issue.

**Comment by maxbrunsfeld** [comment]
@itkovian could you share the version of `vim-mode` that  you're running and post the stack trace that appeared in your notification? Sometimes an error with the same message might have a totally different stack trace.

**Comment by itkovian** [comment]
If I can reproduce it, I will.

**Comment by codykrieger** [comment]
Not quite sure how I did it, but here's my stack trace with vim-mode 0.55.0 and Atom 1.0.1:

```
TypeError: undefined is not a function
  at VimState.module.exports.VimState.processOpStack (/Users/cjk/.atom/packages/vim-mode/lib/vim-state.coffee:268:23)
  at VimState.module.exports.VimState.pushOperations (/Users/cjk/.atom/packages/vim-mode/lib/vim-state.coffee:226:8)
  at ViewModel.confirm (/Users/cjk/.atom/packages/vim-mode/lib/view-models/view-model.coffee:11:15)
  at vim-command-mode-input.VimCommandModeInputElement.confirm (/Users/cjk/.atom/packages/vim-mode/lib/view-models/vim-command-mode-input-element.coffee:46:16)
  at /Users/cjk/.atom/packages/vim-mode/lib/view-models/vim-command-mode-input-element.coffee:36:10
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:626:20)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:534:12)
  at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:468:43)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:736:29
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:778:29
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:740:18)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1151:26)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:772:24
  at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2017:18)
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1987:35)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:770:19)
  at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:733:19)
  at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:444:35)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61)
```

**Comment by maxbrunsfeld** [comment]
@codykrieger Thanks for the report. I think this is a new bug, which I haven't seen before. Have you seen it again? Can you open a separate issue for this?

**Comment by codykrieger** [comment]
@maxbrunsfeld You bet; reported in #759.
